# Generated by Django 3.1.2 on 2020-12-04 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("cykel", "0002_auth_group_autoenrollment_rent_20191125_1451"),
    ]

    operations = [
        migrations.CreateModel(
            name="CykelLogEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(db_index=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("action_type", models.CharField(max_length=200)),
                ("data", models.JSONField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ("-timestamp",),
                "verbose_name": "Log Entry",
                "verbose_name_plural": "Log Entries",
            },
        ),
    ]
