# Generated by Django 2.2.3 on 2019-07-26 17:41

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import macaddress.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bike",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bike_number", models.CharField(max_length=8)),
                (
                    "current_position",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, default=None, null=True, srid=4326
                    ),
                ),
                (
                    "availability_status",
                    models.CharField(
                        choices=[
                            ("DI", "Disabled"),
                            ("IU", "In Use"),
                            ("AV", "Available"),
                        ],
                        default="DI",
                        max_length=2,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("US", "Usable"),
                            ("BR", "Broken"),
                            ("IR", "In Repair"),
                        ],
                        default="US",
                        max_length=2,
                    ),
                ),
                (
                    "bike_type",
                    models.CharField(
                        choices=[
                            ("BI", "Bike"),
                            ("CB", "Cargo Bike"),
                            ("EB", "E-Bike"),
                            ("ES", "E-Scooter"),
                        ],
                        default="BI",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lock",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lock_id", models.CharField(max_length=255)),
                (
                    "lock_type",
                    models.CharField(
                        choices=[("CL", "Combination lock"), ("EL", "Electronic Lock")],
                        default="CL",
                        max_length=2,
                    ),
                ),
                (
                    "mac_address",
                    macaddress.fields.MACAddressField(
                        blank=True, integer=True, null=True
                    ),
                ),
                ("unlock_key", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("DI", "Disabled"), ("AC", "Active")],
                        default="DI",
                        max_length=2,
                    ),
                ),
                ("station_name", models.CharField(max_length=255)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        default=None, null=True, srid=4326
                    ),
                ),
                ("max_bikes", models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name="Rent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rent_start", models.DateTimeField()),
                ("rent_end", models.DateTimeField()),
                (
                    "start_position",
                    django.contrib.gis.db.models.fields.PointField(
                        default=None, null=True, srid=4326
                    ),
                ),
                (
                    "end_position",
                    django.contrib.gis.db.models.fields.PointField(
                        default=None, null=True, srid=4326
                    ),
                ),
                (
                    "bike",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bikesharing.Bike",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bike",
            name="current_station",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="bikesharing.Station",
            ),
        ),
        migrations.AddField(
            model_name="bike",
            name="lock",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="bikesharing.Lock",
            ),
        ),
    ]
