# Generated by Django 2.2.4 on 2019-08-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikesharing', '0002_auto_20190726_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='rent_end',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
