# Generated by Django 2.0.4 on 2018-04-16 16:55

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikesharing', '0002_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='current_position',
            field=django.contrib.gis.db.models.fields.PointField(default=None, null=True, srid=4326),
        ),
    ]
