# Generated by Django 2.0.4 on 2018-04-16 17:39

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikesharing', '0003_bike_current_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='end_position',
            field=django.contrib.gis.db.models.fields.PointField(default=None, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='rent',
            name='start_position',
            field=django.contrib.gis.db.models.fields.PointField(default=None, null=True, srid=4326),
        ),
    ]
