# Generated by Django 2.0.4 on 2018-04-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikesharing', '0004_auto_20180416_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='availability_status',
            field=models.CharField(choices=[('DI', 'Disabled'), ('IU', 'In Use'), ('AV', 'Available')], default='DI', max_length=2),
        ),
        migrations.AddField(
            model_name='bike',
            name='bike_type',
            field=models.CharField(choices=[('FR', 'Fahrrad'), ('LR', 'Lastenrad'), ('EB', 'E-Bike')], default='FR', max_length=2),
        ),
        migrations.AddField(
            model_name='bike',
            name='state',
            field=models.CharField(choices=[('US', 'Usable'), ('BR', 'Broken'), ('IR', 'In Repair'), ('SA', 'Sensor Alert')], default='US', max_length=2),
        ),
    ]
