# Generated by Django 2.2.4 on 2019-08-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bikesharing", "0005_auto_20190821_1801"),
    ]

    operations = [
        migrations.AddField(
            model_name="bike",
            name="battery_voltage",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
