# Generated by Django 2.0.4 on 2018-04-21 10:39

from django.db import migrations, models
import macaddress.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bikesharing', '0005_auto_20180416_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', macaddress.fields.MACAddressField(integer=True, null=True)),
                ('unlock_key', models.UUIDField()),
            ],
        ),
    ]
