# Generated by Django 2.0.4 on 2018-04-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikesharing', '0006_lock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lock',
            name='unlock_key',
            field=models.BinaryField(),
        ),
    ]
