# Generated by Django 2.0.4 on 2018-04-21 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikesharing', '0007_auto_20180421_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='lock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bikesharing.Lock'),
        ),
    ]
