# Generated by Django 2.2.3 on 2019-07-26 16:51

from django.db import migrations, models
import django.db.models.deletion
import macaddress.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bikesharing', '0008_bike_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='lock',
            name='lock_id',
            field=models.CharField(default='testlock', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lock',
            name='lock_type',
            field=models.CharField(choices=[('CL', 'Combination lock'), ('EL', 'Electronic Lock')], default='CL', max_length=2),
        ),
        migrations.AlterField(
            model_name='bike',
            name='bike_type',
            field=models.CharField(choices=[('BI', 'Bike'), ('CB', 'Cargo Bike'), ('EB', 'E-Bike'), ('ES', 'E-Scooter')], default='BI', max_length=2),
        ),
        migrations.AlterField(
            model_name='bike',
            name='lock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bikesharing.Lock'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='state',
            field=models.CharField(choices=[('US', 'Usable'), ('BR', 'Broken'), ('IR', 'In Repair')], default='US', max_length=2),
        ),
        migrations.AlterField(
            model_name='lock',
            name='mac_address',
            field=macaddress.fields.MACAddressField(blank=True, integer=True, null=True),
        ),
        migrations.AlterField(
            model_name='lock',
            name='unlock_key',
            field=models.BinaryField(blank=True, editable=True),
        ),
    ]
