# Generated by Django 2.2.4 on 2019-10-24 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikesharing', '0015_location_accuracy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationtracker',
            old_name='lora_tracker_id',
            new_name='device_id',
        ),
    ]
