# Generated by Django 2.2.4 on 2019-10-25 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikesharing', '0016_auto_20191024_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='battery_voltage',
        ),
    ]
