# Generated by Django 2.2.4 on 2020-02-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bikesharing", "0017_remove_bike_battery_voltage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="source",
            field=models.CharField(
                choices=[("LO", "Lock"), ("TR", "Tracker"), ("US", "User")],
                default="LO",
                max_length=2,
            ),
        ),
    ]
