# Generated by Django 2.2.4 on 2020-03-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikesharing', '0020_locationtracker_internal_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='internal_location',
            field=models.BooleanField(default=False, help_text='Internal locations are not published to the enduser. They are usefull for backup trackers with lower accuracy e.g. wifi trackers.'),
        ),
    ]
