# Generated by Django 2.2.4 on 2020-03-26 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bikesharing", "0022_auto_20200326_1845"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location", old_name="internal_location", new_name="internal",
        ),
    ]
