# Generated by Django 2.2.10 on 2020-06-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bikesharing", "0025_bikesharepreferences_gbfs_system_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="bikesharepreferences",
            name="system_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="bikesharepreferences",
            name="system_short_name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
