# Generated by Django 2.2.13 on 2020-06-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bikesharing", "0029_bike_non_static_bike_id_unique_20200610_1901"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="reported_at",
            field=models.DateTimeField(default=None),
        ),
    ]
