# Generated by Django 2.2.13 on 2020-08-14 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bikesharing", "0031_auto_20200814_1618"),
    ]

    operations = [
        migrations.RemoveField(model_name="bike", name="bike_type",),
    ]
