# Generated by Django 2.2.13 on 2020-08-14 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bikesharing", "0030_auto_20200618_1414"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bike",
            options={"permissions": [("maintain", "Can use maintainance UI")]},
        ),
    ]
