# Generated by Django 2.2.15 on 2020-09-08 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bikesharing", "0034_auto_20200824_2336"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bike",
            options={"permissions": [("maintain", "Can use maintainance UI")]},
        ),
    ]
