# Generated by Django 2.2.15 on 2020-10-12 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bikesharing", "0035_auto_20200908_1430"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="tracker",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="bikesharing.LocationTracker",
            ),
        ),
    ]
