# Generated by Django 2.2.15 on 2020-10-12 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bikesharing", "0036_auto_20201012_1351"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bike",
            name="lock",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="bikesharing.Lock",
            ),
        ),
    ]
