# Generated by Django 2.2.15 on 2020-10-26 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bikesharing", "0040_remove_lock_form_factor_20201020_1047"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bike",
            options={"permissions": [("maintain", "Can use maintenance UI")]},
        ),
    ]
