# Generated by Django 3.1.2 on 2020-11-20 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bikesharing", "0042_location_tracker_type_20201120_1700"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="locationtracker",
            name="tracker_type_str",
        ),
    ]
