# Generated by Django 3.1.2 on 2020-12-04 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bikesharing", "0045_rent_position_locations_20201204_2022"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rent",
            name="end_position",
        ),
        migrations.RemoveField(
            model_name="rent",
            name="start_position",
        ),
    ]
