# Generated by Django 3.1.2 on 2021-08-24 13:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bikesharing', '0046_rent_remove_position_20201204_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='non_static_bike_uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text="A temporary ID used in public APIs,\n        rotating it's value after each rent to protect users privacy.", unique=True),
        ),
        migrations.AlterField(
            model_name='bikesharepreferences',
            name='gbfs_hide_bikes_after_location_report_hours',
            field=models.IntegerField(default=1, help_text="Time period (in hours) after the vehicles will\n         be hidden from GBFS, if there was no location report.\n         Needs 'Gbfs hide bikes after location report silence' activated."),
        ),
        migrations.AlterField(
            model_name='bikesharepreferences',
            name='gbfs_hide_bikes_after_location_report_silence',
            field=models.BooleanField(default=False, help_text='If activated, vehicles will disappear from GBFS,\n         if there was no location report in the configured time period.'),
        ),
        migrations.AlterField(
            model_name='location',
            name='internal',
            field=models.BooleanField(default=False, help_text='Internal locations are not published to the enduser.\n         They are useful for backup trackers with lower accuracy e.g. wifi trackers.'),
        ),
        migrations.AlterField(
            model_name='locationtracker',
            name='internal',
            field=models.BooleanField(default=False, help_text="Internal trackers don't publish their locations to the enduser.\n         They are useful for backup trackers with lower accuracy e.g. wifi trackers."),
        ),
    ]
